# Generated by Django 5.1.7 on 2025-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corecode", "0001_initial"),
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentclass",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to="staffs.staff"
            ),
        ),
    ]
