# Generated by Django 5.1.7 on 2025-04-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_add_initial_session'),
        ('corecode', '0002_initial'),
    ]

    operations = [
    ]
